import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Dashboard from "./dashboard/page";
import { Toaster } from "react-hot-toast";
import Providers from "@/Providers/Providers";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col relative overflow-hidden">
        <div className="flex-1">
          <Providers>
            {children}
          </Providers>
          <Toaster position="top-center"></Toaster>
        </div>
      </body>
    </html>
  );
}
